from __future__ import annotations


VISUAL_STORY_OBJECTS = {
    "phone_account",
    "salary_balance",
    "emi_stack",
    "debt_pressure",
    "inflation_basket",
    "sip_jar",
    "portfolio_grid",
    "emergency_buffer",
}


CONCEPT_TO_SCENE_ROLE = {
    "salary_drain": "pressure",
    "salary_depletion": "pressure",
    "lifestyle_inflation": "pressure",
    "expense_leakage": "pressure",
    "emi_pressure": "pressure",
    "rent_burden": "pressure",
    "tax_drain": "pressure",
    "subscription_leak": "pressure",
    "debt_trap": "mechanism",
    "inflation_erosion": "mechanism",
    "real_return": "mechanism",
    "fd_vs_inflation": "mechanism",
    "risk_return": "mechanism",
    "diversification": "mechanism",
    "opportunity_cost": "mechanism",
    "sip_growth": "solution",
    "compounding": "solution",
    "compound_growth": "solution",
    "recap_system": "resolution",
    "emergency_fund": "solution",
    "savings_rate": "solution",
    "fomo_risk": "turning_point",
    "speculation_risk": "turning_point",
    "decay": "pressure",
    "growth": "solution",
    "comparison": "mechanism",
    "risk": "mechanism",
    "definition": "mechanism",
    "emphasis": "turning_point",
}


CONCEPT_TO_OBJECTS = {
    "salary_drain": ["phone_account", "salary_balance"],
    "salary_depletion": ["phone_account", "salary_balance"],
    "lifestyle_inflation": ["phone_account", "salary_balance"],
    "expense_leakage": ["phone_account", "salary_balance"],
    "rent_burden": ["phone_account", "salary_balance"],
    "tax_drain": ["phone_account", "salary_balance"],
    "subscription_leak": ["phone_account", "salary_balance"],
    "emi_pressure": ["emi_stack", "salary_balance"],
    "debt_trap": ["debt_pressure", "phone_account"],
    "inflation_erosion": ["inflation_basket"],
    "real_return": ["inflation_basket", "salary_balance"],
    "fd_vs_inflation": ["inflation_basket", "salary_balance"],
    "sip_growth": ["sip_jar"],
    "compounding": ["sip_jar"],
    "compound_growth": ["sip_jar"],
    "recap_system": ["salary_balance", "emi_stack", "sip_jar", "portfolio_grid", "emergency_buffer"],
    "savings_rate": ["sip_jar", "salary_balance"],
    "emergency_fund": ["emergency_buffer"],
    "fomo_risk": ["portfolio_grid"],
    "speculation_risk": ["portfolio_grid"],
    "risk_return": ["portfolio_grid"],
    "diversification": ["portfolio_grid"],
    "opportunity_cost": ["sip_jar", "salary_balance"],
    "decay": ["salary_balance"],
    "growth": ["sip_jar"],
    "comparison": ["phone_account"],
    "risk": ["debt_pressure"],
    "definition": ["phone_account"],
    "emphasis": ["phone_account"],
}


CONCEPT_VISUAL_QUESTIONS = {
    "salary_drain": "Where did the salary go?",
    "salary_depletion": "Where did the salary go?",
    "lifestyle_inflation": "Why does a raise not create savings?",
    "expense_leakage": "What invisible drain is eating the salary?",
    "emi_pressure": "How do small EMIs become one big leak?",
    "debt_trap": "Why does paying not reduce the balance?",
    "inflation_erosion": "Why does the same balance buy less?",
    "real_return": "What is the actual return after inflation?",
    "fd_vs_inflation": "Is the FD actually growing or shrinking?",
    "sip_growth": "What changes when returns start earning returns?",
    "compounding": "Why does time matter more than amount?",
    "compound_growth": "What changes when returns start earning returns?",
    "recap_system": "What system keeps the money plan alive?",
    "savings_rate": "How much is actually getting saved each month?",
    "emergency_fund": "What absorbs the next financial shock?",
    "fomo_risk": "What happens when emotion becomes the strategy?",
    "speculation_risk": "What happens when emotion becomes the strategy?",
    "risk_return": "What is the risk that comes with the return?",
    "diversification": "What changes when one bet becomes a system?",
    "opportunity_cost": "What is the cost of not investing?",
}
