from __future__ import annotations

from typing import Any


CONCEPT_TAXONOMY: dict[str, dict[str, Any]] = {
    "salary_drain": {
        "signals": [
            r"\bsalary\b.*\b(gone|drain|drains|vanish|vanishes|disappear|disappears|left|broke|spent|empty)\b",
            r"\bpaycheck\s+to\s+paycheck\b",
            r"\bnothing\s+left\b",
            r"\bsalary\b.*\b(month|end|day)\b.*\b(nothing|zero|empty|left)\b",
        ],
        "type": "risk",
        "visual_pattern": "income_drain_waterfall",
    },
    "emi_pressure": {
        "signals": [
            r"\bemi\b.*\b(stack|pressure|joins?|leaves?|starts?|takes?|fixed|month|monthly)\b",
            r"\b(phone|bike|car|personal)\s+emi\b",
            r"\bmultiple\s+emis?\b",
            r"\bfixed payments?\b",
            r"\binstalments?\b.*\b(stack|month|salary|cash)\b",
        ],
        "type": "risk",
        "visual_pattern": "emi_stack_pressure",
    },
    "sip_growth": {
        "signals": [
            r"\bsip\b",
            r"monthly investment.*compound",
            r"monthly investment.*returns?",
            r"invest.*per month.*returns?",
            r"small investments?.*corpus",
            r"corpus.*grows?",
        ],
        "type": "growth",
        "visual_pattern": "sip_compound_growth",
    },
    "lifestyle_inflation": {
        "signals": [
            r"lifestyle inflation",
            r"spend more",
            r"expenses increase",
            r"raise.*spend",
            r"raise.*upgrade.*lifestyle",
            r"income.*upgrade",
            r"income\s+rises?.*savings\s+stay",
            r"lifestyle\s+rises?",
            r"lifestyle\s+absorbs?",
            r"spending\s+rises?.*savings",
            r"earn more.*buy",
            r"salary rises.*expenses rise faster",
            r"fancy phone",
            r"brand new car",
            r"fancy wedding",
        ],
        "type": "risk",
        "visual_pattern": "income_vs_spending_divergence",
    },
    "debt_trap": {
        "signals": [
            r"\bdebt\s+trap\b",
            r"\bcredit\s+card\b.*\binterest\b",
            r"\bcredit\s+card\b.*\bbills?\b",
            r"\bemi\b.*\bburden\b",
            r"\bloan\b.*\bspiral\b",
            r"\bborrow\b.*\brepay\b",
            r"\bdebt\b.*\bgrows?\b",
            r"\binterest\b.*\bcompound\b.*\bdebt\b",
            r"\bminimum\s+payment\b",
            r"\bminimum\s+dues?\b",
            r"\boutstanding\s+balance\b",
        ],
        "type": "risk",
        "visual_pattern": "debt_growth_spiral",
    },
    "inflation_erosion": {
        "signals": [
            r"inflation.*value",
            r"purchasing power",
            r"real returns",
            r"fd.*inflation",
            r"price.*rise",
            r"cost.*increase",
            r"buying power",
        ],
        "type": "risk",
        "visual_pattern": "value_erosion_over_time",
    },
    "compound_growth": {
        "signals": [
            r"\bcompound\b",
            r"\bcompounding\b",
            r"grows over time",
            r"long.?term.*investment",
            r"wealth.*build",
        ],
        "type": "growth",
        "visual_pattern": "exponential_growth_curve",
    },
    "fomo_risk": {
        "signals": [
            r"\bfomo\b",
            r"\bspeculat\w+\b",
            r"\blife savings\b",
            r"\bdon'?t understand\b",
            r"\bdo not understand\b",
            r"\bhype\b.*\b(invest|buy|trade)\b",
            r"\bpanic\b.*\b(sell|buy|starts?)\b",
            r"\benter\b.*\blate\b",
            r"\beveryone talks about\b",
            r"\bemotion\b.*\bfinance\b",
            r"\bcryptocurrency\b|\bcrypto\b",
        ],
        "type": "risk",
        "visual_pattern": "speculation_vs_investing",
    },
    "diversification": {
        "signals": [
            r"\bdiversif\w+\b",
            r"\bone basket\b",
            r"\bone stock\b",
            r"\ball eggs\b",
            r"\basset class\w*\b",
            r"\bspread\b.*\b(risk|investment|assets?)\b",
        ],
        "type": "comparison",
        "visual_pattern": "diversification_grid",
    },
    "opportunity_cost": {
        "signals": [
            r"instead.*invest",
            r"could have",
            r"if.*invested",
            r"missed.*returns",
            r"cost.*not investing",
        ],
        "type": "comparison",
        "visual_pattern": "path_comparison_split",
    },
    "savings_rate": {
        "signals": [
            r"save.*percent",
            r"saving.*income",
            r"%.*saving",
            r"invest.*salary",
            r"put aside",
            r"automate.*save",
            r"budget",
            r"track",
            r"allocate",
        ],
        "type": "process",
        "visual_pattern": "income_allocation_breakdown",
    },
    "tax_efficiency": {
        "signals": [
            r"tax.*save",
            r"80c",
            r"deduction",
            r"tax.*exempt",
            r"post.?tax",
            r"pre.?tax",
            r"ppf",
            r"nps",
            r"elss",
        ],
        "type": "comparison",
        "visual_pattern": "before_after_tax_split",
    },
    "risk_return": {
        "signals": [
            r"risk.*return",
            r"safe.*low",
            r"volatile.*high",
            r"fd.*safe",
            r"equity.*risk",
            r"fixed.*return",
            r"equity.*debt",
            r"while debt is stable",
        ],
        "type": "comparison",
        "visual_pattern": "risk_return_spectrum",
    },
    "expense_leakage": {
        "signals": [
            r"subscription",
            r"subscriptions",
            r"expense",
            r"expenses",
            r"spending",
            r"dining out",
            r"ordering in",
            r"premium",
            r"leak",
            r"leaks",
        ],
        "type": "risk",
        "visual_pattern": "expense_leakage_ladder",
    },
    "emergency_fund": {
        "signals": [
            r"emergency fund",
            r"cash buffer",
            r"medical emergency",
            r"lose your job",
        ],
        "type": "definition",
        "visual_pattern": "buffer_protection_split",
    },
}


CONCEPT_MATCH_PRIORITY = {
    "sip_growth": 100,
    "debt_trap": 95,
    "emi_pressure": 90,
    "salary_drain": 120,
    "lifestyle_inflation": 80,
    "inflation_erosion": 75,
    "fomo_risk": 72,
    "diversification": 70,
    "compound_growth": 62,
    "emergency_fund": 60,
    "opportunity_cost": 55,
    "savings_rate": 50,
    "tax_efficiency": 50,
    "risk_return": 48,
    "expense_leakage": 35,
}
