"""Constants used by the legacy scene builder coordinator."""

MIN_BEAT_DURATION = 1.2
DIRECTED_MIN_BEAT_DURATION = 1.5
COMPONENT_DURATION_WEIGHTS = {
    "StatCard": 1.0,
    "HighlightText": 0.9,
    "ConceptCard": 1.0,
    "ConceptCardScene": 1.0,
    "RiskCard": 1.1,
    "RiskCardScene": 1.1,
    "FlowBar": 1.4,
    "FlowDiagram": 1.6,
    "BalanceBar": 1.5,
    "CalculationStrip": 1.6,
    "SplitComparison": 1.3,
    "SplitComparisonScene": 1.3,
    "GrowthChart": 1.5,
    "GrowthChartScene": 1.5,
    "InflationErosionVisualizer": 2.8,
    "LifestyleCreepVisualizer": 2.4,
    "EMIStackVisualizer": 2.5,
    "FOMOPriceCrashVisualizer": 2.4,
    "PortfolioDiversificationVisualizer": 2.4,
    "SmallLeaksAccumulator": 2.3,
    "RiskReturnVisualizer": 2.4,
    "EmergencyFundVisualizer": 2.4,
    "OutroRecapVisualizer": 2.2,
    "UniversalMechanismRenderer": 2.3,
    "StepFlow": 1.4,
    "StepFlowScene": 1.4,
    "MoneyFlowDiagram": 1.8,
    "DebtSpiralVisualizer": 1.8,
    "SIPGrowthEngine": 1.9,
}
PATTERN_PRIORITY = {
    "MoneyFlowDiagram": 7,
    "DebtSpiralVisualizer": 7,
    "SIPGrowthEngine": 7,
    "InflationErosionVisualizer": 7,
    "LifestyleCreepVisualizer": 7,
    "EMIStackVisualizer": 7,
    "FOMOPriceCrashVisualizer": 7,
    "PortfolioDiversificationVisualizer": 7,
    "SmallLeaksAccumulator": 7,
    "RiskReturnVisualizer": 7,
    "EmergencyFundVisualizer": 7,
    "OutroRecapVisualizer": 7,
    "UniversalMechanismRenderer": 6,
    "GrowthChart": 6,
    "SplitComparison": 6,
    "FlowDiagram": 6,
    "BalanceBar": 6,
    "NumericComparison": 5,
    "RiskCard": 3,
    "StepFlow": 2,
    "ConceptCard": 1,
}
REQUIRED_BEAT_DATA = {
    "MoneyFlowDiagram": ("source", "flows", "remainder"),
    "DebtSpiralVisualizer": ("principal", "monthly_interest"),
    "SIPGrowthEngine": ("monthly_sip", "final_corpus"),
    "InflationErosionVisualizer": ("start", "end"),
    "LifestyleCreepVisualizer": ("start_income", "end_income"),
    "EMIStackVisualizer": ("salary", "emis", "remaining"),
    "FOMOPriceCrashVisualizer": ("points",),
    "PortfolioDiversificationVisualizer": ("assets",),
    "SmallLeaksAccumulator": ("leaks", "monthly_loss"),
    "RiskReturnVisualizer": ("safe_asset", "growth_asset"),
    "EmergencyFundVisualizer": ("buffer_label", "shock_label"),
    "UniversalMechanismRenderer": ("cinematic_events",),
    "CalculationStrip": ("steps",),
    "SplitComparison": ("left", "right"),
}
DOMINANT_COMPONENTS = {
    "MoneyFlowDiagram",
    "DebtSpiralVisualizer",
    "SIPGrowthEngine",
    "InflationErosionVisualizer",
    "LifestyleCreepVisualizer",
    "EMIStackVisualizer",
    "FOMOPriceCrashVisualizer",
    "PortfolioDiversificationVisualizer",
    "SmallLeaksAccumulator",
    "RiskReturnVisualizer",
    "EmergencyFundVisualizer",
    "OutroRecapVisualizer",
    "UniversalMechanismRenderer",
    "GrowthChart",
    "FlowDiagram",
    "SplitComparison",
}
DOMINANT_SHARE = 0.64
TEXT_COMPONENTS = {"StatCard", "HighlightText", "ConceptCard", "ConceptCardScene", "RiskCard", "RiskCardScene"}
PHASE_WEIGHT_MULTIPLIERS = {
    "drain": 1.4,
    "spiral": 1.4,
    "growth": 1.4,
    "erosion": 1.4,
    "intro": 0.75,
    "principal": 0.75,
    "contribution": 0.75,
    "today": 0.75,
    "remainder": 0.95,
    "consequence": 0.95,
    "corpus": 0.95,
    "future": 0.95,
    "income_base": 0.75,
    "raise_arrives": 1.1,
    "expenses_follow": 1.45,
    "gap_revealed": 1.0,
    "first_emi": 0.75,
    "stacking": 1.45,
    "pressure": 1.0,
    "rise": 0.9,
    "crash": 1.55,
    "loss": 1.0,
    "concentrated": 0.8,
    "spread": 1.35,
    "impact": 1.05,
    "first_leak": 0.8,
    "repeat": 1.45,
    "month_end": 1.0,
}
